// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: udmvlyrvcmrvxzyczpca

class SupabaseConfig {
  static const String supabaseUrl = 'https://udmvlyrvcmrvxzyczpca.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkbXZseXJ2Y21ydnh6eWN6cGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MTUwNTAsImV4cCI6MjA3NjA5MTA1MH0.G3qzbI-eGz4Y0nxjgDvt8J50SL4cvH40G0lx1B2y4OU';
}
